export enum RQ_KEY {
  GET_COMPLETED_TXS = 'get_complete_transactions',
  GET_TXS = 'get_transactions',
  PUBLISH_TX = 'publish_transaction',
  POSTS = 'posts',
  GET_SHEETS = 'get_sheets',
  GET_BOOKMARKED_SHEETS = 'get_bookmarked_sheets',
  CHECK_BOOKMARKED_SHEETS = 'check_bookmarked_sheets',
  GET_EVENTS = 'get_events',
  GET_POSTS = 'get_posts',
  GET_METADATAS = 'get_metadatas',
  GET_METADATA = 'get_metadata',
  GET_NFT_METADATA = 'get_nft_metadata',
  GET_NFTS = 'get_nfts',
  GET_ALL_NFTS = 'get_all_nfts',
  GET_PRESET_METADATAS = 'get_preset_metadatas',
  GET_LATEST_CRYPTO_NEWS = 'get_latest_crypto_news',
}
